### ISSUE TITLE
Error while running the app

### ISSUE THREAD

**Issue by dewanganlakhan** [Louie1505/trendsdotnet#1]
Hey @Louie1505 ,

I think you have done good job on creating this project. Congrats!! buddy.

I tried to run the application but getting some json object reference not set to object error.

Is this project is completed or is there any time line to get it working?

**Comment by Louie1505** [comment]
Hi @dewanganlakhan,
Thanks so much for your interest in my project! Unfortunately this is still very WIP, and since it's just something I will eventually need for another project, it's not super high on my list right now - Though I do plan on releasing to nuget as a package once done. 
If you need a wrapper around the API now then I reccomend this nodejs package which I've used in the past, might be of interest to you - https://github.com/pat310/google-trends-api :) Thanks again!
